- name: Linux hosts ping
  hosts: all
  become_method: sudo
  vars:
    playbookfolder: '/Linux'
  tasks:
    - include_tasks: '{{ playbookfolder }}/uname.yaml'
    - include_tasks: '{{ playbookfolder }}/sudo.yaml'
    - include_tasks: '{{ playbookfolder }}/device.yaml'
